<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="DESKTOP-LAST3N4" name="pytest" skipped="1" tests="2" time="0.080" timestamp="2020-01-27T12:36:26.452585"><testcase classname="test_sample2" file="test_sample2.py" line="3" name="test_file2_method1" time="0.002"><failure message="AssertionError: test failed because x=5 y=6
assert 5 == 6
  -5
  +6">@pytest.mark.set1
    #@pytest.mark.xfail
    def test_file2_method1():
        x = 5
        y = 6
        assert x + 1 == y, &quot;test failed&quot;
&gt;       assert x == y, &quot;test failed because x=&quot; + str(x) + &quot; y=&quot; + str(y)
E       AssertionError: test failed because x=5 y=6
E       assert 5 == 6
E         -5
E         +6

test_sample2.py:10: AssertionError</failure></testcase><testcase classname="test_sample2" file="test_sample2.py" line="11" name="test_file2_method2" time="0.001"><skipped message="unconditional skip" type="pytest.skip">test_sample2.py:12: unconditional skip</skipped></testcase></testsuite></testsuites>